### ISSUE TITLE
Upload cache.tsv to data.world

### ISSUE THREAD

**Issue by vmarkovtsev** [erikbern/eigenstuff#1]
Hey Erik, how about uploading cache.tsv file to [data.world](https://data.world) (create the dataset). I think it matches the built-in facilities nicely there.

**Comment by erikbern** [comment]
sure, go ahead and do it if you want to :)

**Comment by vmarkovtsev** [comment]
https://data.world/vmarkovtsev/from-language-x-to-y

I chose CC-0, please corect me if I was wrong.

**Comment by erikbern** [comment]
cool, thanks!
